package com.kd.model.track.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGeneralinfo<M extends BaseGeneralinfo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "generalinfo";

	/**
	 * 自增ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 用户名
	 */
	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	/**
	 * 用户名
	 */
	public java.lang.String getUserName() {
		return get("userName");
	}

	/**
	 * sessionID
	 */
	public void setSession(java.lang.String session) {
		set("session", session);
	}

	/**
	 * sessionID
	 */
	public java.lang.String getSession() {
		return get("session");
	}

	/**
	 * 访问请求
	 */
	public void setUri(java.lang.String uri) {
		set("uri", uri);
	}

	/**
	 * 访问请求
	 */
	public java.lang.String getUri() {
		return get("uri");
	}

	/**
	 * 参数
	 */
	public void setParas(java.lang.String paras) {
		set("paras", paras);
	}

	/**
	 * 参数
	 */
	public java.lang.String getParas() {
		return get("paras");
	}

	/**
	 * 头信息
	 */
	public void setHeader(java.lang.String header) {
		set("header", header);
	}

	/**
	 * 头信息
	 */
	public java.lang.String getHeader() {
		return get("header");
	}

	/**
	 * 返回状态
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	/**
	 * 返回状态
	 */
	public java.lang.String getStatus() {
		return get("status");
	}

	/**
	 * 请求时间
	 */
	public void setTime(java.lang.String time) {
		set("time", time);
	}

	/**
	 * 请求时间
	 */
	public java.lang.String getTime() {
		return get("time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
